### ISSUE TITLE
incluir favicon e mudar titulo

### ISSUE THREAD

**Issue by caio-emidio** [ukecode/ukecode-web-page#25]
![image](https://user-images.githubusercontent.com/5342402/80975275-cc3b8200-8e19-11ea-8fd4-b52cc56ede2b.png)

Acredito que somente UkeCode esta muito simples.

UkeCode - [INCLUIR FRASE DE EFEITO DO KAIO AQUI]

**Comment by caio-emidio** [comment]
Apenas para nosso controle,
Quando fechar assim podemos colocar:

Aplicado em Desenvolvimento. 
ou
Bug Inexistente

**Comment by KelvinyHenrique** [comment]
@caio-emidio Ok
