### ISSUE TITLE
Projetos sem imagem.

### ISSUE THREAD

**Issue by caio-emidio** [ukecode/ukecode-web-page#26]
![image](https://user-images.githubusercontent.com/5342402/80975465-0b69d300-8e1a-11ea-8498-05258ec52b3b.png)

Ou criamos uma regra que todo projeto tem que ter img ou criamos uma img default para projetos que tiverem photo="".
Posso fazer isso no backend. Ou faz aqui no front. Apenas decidir :)

**Comment by KelvinyHenrique** [comment]
Tem como fazer isso no backend? tá 3 horas tentando fazer essa desgraça e não consigo.

**Comment by caio-emidio** [comment]
@KelvinyHenrique Sim

**Comment by caio-emidio** [comment]
@KelvinyHenrique Me passa a imagem padrão q farei o desenvolvimento para a próxima semana

**Comment by caio-emidio** [comment]
![image](https://user-images.githubusercontent.com/5342402/82800737-1392bc80-9e74-11ea-8f5d-315e2533d2bf.png)

**Comment by caio-emidio** [comment]
Ja solucionei isso :) criei imagens para todos os projetos ;)
