### ISSUE TITLE
Animacao do Foguete so funciona uma vez

### ISSUE THREAD

**Issue by caio-emidio** [ukecode/ukecode-web-page#28]
Ao executar duas vezes a animacao do Foguete notamos que a pagina volta pra cima. mas nao acontece a animacao.

Testado em Chrome.

**Comment by caio-emidio** [comment]
Kelviny, 

Erro perpetua,
Agora funciona vez sim
vez nao
e dai vez sim

Testado em Chrome :)

**Comment by KelvinyHenrique** [comment]
@caio-emidio Teste aqui no Chrome não deu erro nenhuma vez

**Comment by caio-emidio** [comment]
agora funciona vez sim vez nao.
ja demonstrei ao kelviny, mas ao meu ver pode ficar assim. esta otimo :)
